plugins {
    id 'com.android.application'
}
android {
    namespace 'com.gn.gpstripmeter'
    compileSdk 35
    defaultConfig {
        applicationId 'com.gn.gpstripmeter.huawei.v13'
        minSdk 23
        targetSdk 28
        versionCode 13
        versionName '13.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
